version: 1.0.{build}

branches:
  only:
    - master

os: Windows Server 2012

clone_folder: c:\projects\xash\xash3d

build:
  project: xash.sln

  verbosity: quiet

before_build:
  - git clone -q --branch=master https://github.com/MrYadro/SDL2.git C:\projects\xash\SDL2
  - git clone -q --branch=master https://github.com/SDLash3D/halflife.git C:\projects\xash\halflife
  - git clone -q --branch=master https://github.com/SDLash3D/XashXT.git C:\projects\xash\XashXT
