version: 1.0.{build}

branches:
  only:
    - master

os: Windows Server 2012

clone_folder: c:\projects\xash\xash3d

build:
  project: xash.sln

  verbosity: normal

before_build:
  - git clone -q --branch=master https://github.com/spurious/SDL-mirror.git C:\projects\xash\SDL2
  - git clone -q --branch=master https://github.com/SDLash3D/halflife.git C:\projects\xash\halflife
  - git clone -q --branch=master https://github.com/SDLash3D/XashXT.git C:\projects\xash\XashXT

after_build:
  - 7z a -tzip archive.zip c:\projects\xash\xash3d\Debug\
  - curl --upload-file archive.zip https://transfer.sh/archive.zip

notifications:

  - provider: Webhook
    url: https://webhooks.gitter.im/e/29ef45a57585978bf71a